package com.fountainframework.core.serialize;

import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Creates and configures the shared {@link ObjectMapper} for the Fountain framework.
 * <p>
 * Configuration choices:
 * <ul>
 *   <li>Fails fast on unknown properties disabled — lenient by default for API evolution</li>
 *   <li>Empty beans serialization allowed — avoids surprise exceptions on DTOs with no getters</li>
 *   <li>Auto-discovers Jackson performance modules (Blackbird, Afterburner) if present on
 *       the classpath — these replace reflective field access with generated bytecode,
 *       yielding ~20-30% throughput improvement on JSON-heavy workloads</li>
 * </ul>
 * <p>
 * A single instance is shared between {@link JacksonBodyReader} and {@link JacksonResponseWriter}
 * to avoid duplicate serializer caches and redundant class introspection.
 */
public final class ObjectMapperFactory {

    private static final Logger log = LoggerFactory.getLogger(ObjectMapperFactory.class);

    private ObjectMapperFactory() {}

    /**
     * Creates a production-tuned {@link ObjectMapper}.
     * <p>
     * Called once at application startup. The returned instance is thread-safe
     * and should be shared across all serialization points.
     */
    public static ObjectMapper create() {
        ObjectMapper mapper = new ObjectMapper();

        // Lenient deserialization — don't break on extra fields from newer API clients
        mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);

        // Don't fail on POJOs with no properties (e.g. marker types, empty responses)
        mapper.configure(SerializationFeature.FAIL_ON_EMPTY_BEANS, false);

        // Auto-discover performance modules on the classpath.
        // findAndRegisterModules() picks up Blackbird, Afterburner, JavaTimeModule, etc.
        // via ServiceLoader — zero config, just add the dependency.
        mapper.findAndRegisterModules();

        int moduleCount = mapper.getRegisteredModuleIds().size();
        if (moduleCount > 0) {
            log.info("Jackson ObjectMapper initialized with {} module(s): {}",
                    moduleCount, mapper.getRegisteredModuleIds());
        } else {
            log.info("Jackson ObjectMapper initialized (no optional modules on classpath)");
        }

        return mapper;
    }
}
